title: HIGHTIDE
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY
url: http://sonak-lll.github.io
paginate_path: "blog/page:num/"
permalink: blog/:title/
markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5
navigation:
  - title: Home
    url: /index.html
  - title: Articles
    url: /articles
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: 
  twitter: 
  facebook: 
  email: 
  linkedin: 

google_analytics: 

disqus:
    shortname: 

header: large

